version: '3.5'

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: postgres
    ports:
      - '6060:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=SagTech
    networks:
      - my_network

  nest:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: nest-app
    environment:
      - PORT=3000
      - JWT_SECRET=secret
      - ACCOUNT_PORT=3001
      - POSTS_PORT=3002
    ports:
      - '5050:3000'
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
